import XCTest
import TestLibrary

final class DTests: XCTestCase, TimeLimit {
    let timeLimit: TimeInterval = 2.0

    func testExample() throws {
        let cases: [TestCase] = [
            (#filePath, #line, """
                3 9
                .........
                .........
                .........
                """, """
                1
                """),
            (#filePath, #line, """
                10 10
                ..........
                #...#.....
                ..........
                ..........
                ..........
                ....#.....
                .#......#.
                ..........
                ..........
                ..........
                """, """
                6
                """),
        ]
        try cases.forEach(solve)
    }
}