// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "TYPICAL90",
    dependencies: [],
    targets: [
        .target(name: "001"),
        .testTarget(name: "001Tests", dependencies: ["001", "TestLibrary"]),
        .target(name: "002"),
        .testTarget(name: "002Tests", dependencies: ["002", "TestLibrary"]),
        .target(name: "003"),
        .testTarget(name: "003Tests", dependencies: ["003", "TestLibrary"]),
        .target(name: "004"),
        .testTarget(name: "004Tests", dependencies: ["004", "TestLibrary"]),
        .target(name: "005"),
        .testTarget(name: "005Tests", dependencies: ["005", "TestLibrary"]),
        .target(name: "006"),
        .testTarget(name: "006Tests", dependencies: ["006", "TestLibrary"]),
        .target(name: "007"),
        .testTarget(name: "007Tests", dependencies: ["007", "TestLibrary"]),
        .target(name: "008"),
        .testTarget(name: "008Tests", dependencies: ["008", "TestLibrary"]),
        .target(name: "009"),
        .testTarget(name: "009Tests", dependencies: ["009", "TestLibrary"]),
        .target(name: "010"),
        .testTarget(name: "010Tests", dependencies: ["010", "TestLibrary"]),
        .target(name: "011"),
        .testTarget(name: "011Tests", dependencies: ["011", "TestLibrary"]),
        .target(name: "012"),
        .testTarget(name: "012Tests", dependencies: ["012", "TestLibrary"]),
        .target(name: "013"),
        .testTarget(name: "013Tests", dependencies: ["013", "TestLibrary"]),
        .target(name: "014"),
        .testTarget(name: "014Tests", dependencies: ["014", "TestLibrary"]),
        .target(name: "015"),
        .testTarget(name: "015Tests", dependencies: ["015", "TestLibrary"]),
        .target(name: "016"),
        .testTarget(name: "016Tests", dependencies: ["016", "TestLibrary"]),
        .target(name: "017"),
        .testTarget(name: "017Tests", dependencies: ["017", "TestLibrary"]),
        .target(name: "018"),
        .testTarget(name: "018Tests", dependencies: ["018", "TestLibrary"]),
        .target(name: "019"),
        .testTarget(name: "019Tests", dependencies: ["019", "TestLibrary"]),
        .target(name: "020"),
        .testTarget(name: "020Tests", dependencies: ["020", "TestLibrary"]),
        .target(name: "021"),
        .testTarget(name: "021Tests", dependencies: ["021", "TestLibrary"]),
        .target(name: "022"),
        .testTarget(name: "022Tests", dependencies: ["022", "TestLibrary"]),
        .target(name: "023"),
        .testTarget(name: "023Tests", dependencies: ["023", "TestLibrary"]),
        .target(name: "TestLibrary", path: "Tests/TestLibrary"),
    ]
)