// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "TYPICAL90",
    dependencies: [],
    targets: [
        .target(name: "001", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "001Tests", dependencies: ["001", "TestLibrary"]),
        .target(name: "002", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "002Tests", dependencies: ["002", "TestLibrary"]),
        .target(name: "003", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "003Tests", dependencies: ["003", "TestLibrary"]),
        .target(name: "004", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "004Tests", dependencies: ["004", "TestLibrary"]),
        .target(name: "005", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "005Tests", dependencies: ["005", "TestLibrary"]),
        .target(name: "006", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "006Tests", dependencies: ["006", "TestLibrary"]),
        .target(name: "007", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "007Tests", dependencies: ["007", "TestLibrary"]),
        .target(name: "008", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "008Tests", dependencies: ["008", "TestLibrary"]),
        .target(name: "009", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "009Tests", dependencies: ["009", "TestLibrary"]),
        .target(name: "010", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "010Tests", dependencies: ["010", "TestLibrary"]),
        .target(name: "011", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "011Tests", dependencies: ["011", "TestLibrary"]),
        .target(name: "012", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "012Tests", dependencies: ["012", "TestLibrary"]),
        .target(name: "013", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "013Tests", dependencies: ["013", "TestLibrary"]),
        .target(name: "014", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "014Tests", dependencies: ["014", "TestLibrary"]),
        .target(name: "015", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "015Tests", dependencies: ["015", "TestLibrary"]),
        .target(name: "016", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "016Tests", dependencies: ["016", "TestLibrary"]),
        .target(name: "017", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "017Tests", dependencies: ["017", "TestLibrary"]),
        .target(name: "018", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "018Tests", dependencies: ["018", "TestLibrary"]),
        .target(name: "019", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "019Tests", dependencies: ["019", "TestLibrary"]),
        .target(name: "020", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "020Tests", dependencies: ["020", "TestLibrary"]),
        .target(name: "021", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "021Tests", dependencies: ["021", "TestLibrary"]),
        .target(name: "022", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "022Tests", dependencies: ["022", "TestLibrary"]),
        .target(name: "023", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "023Tests", dependencies: ["023", "TestLibrary"]),
        .target(name: "024", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "024Tests", dependencies: ["024", "TestLibrary"]),
        .target(name: "025", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "025Tests", dependencies: ["025", "TestLibrary"]),
        .target(name: "026", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "026Tests", dependencies: ["026", "TestLibrary"]),
        .target(name: "027", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "027Tests", dependencies: ["027", "TestLibrary"]),
        .target(name: "028", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "028Tests", dependencies: ["028", "TestLibrary"]),
        .target(name: "029", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "029Tests", dependencies: ["029", "TestLibrary"]),
        .target(name: "030", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "030Tests", dependencies: ["030", "TestLibrary"]),
        .target(name: "031", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "031Tests", dependencies: ["031", "TestLibrary"]),
        .target(name: "032"),
        .testTarget(name: "032Tests", dependencies: ["032", "TestLibrary"]),
        .target(name: "033", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "033Tests", dependencies: ["033", "TestLibrary"]),
        .target(name: "034", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "034Tests", dependencies: ["034", "TestLibrary"]),
        .target(name: "035", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "035Tests", dependencies: ["035", "TestLibrary"]),
        .target(name: "036", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "036Tests", dependencies: ["036", "TestLibrary"]),
        .target(name: "037", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "037Tests", dependencies: ["037", "TestLibrary"]),
        .target(name: "038", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "038Tests", dependencies: ["038", "TestLibrary"]),
        .target(name: "039", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "039Tests", dependencies: ["039", "TestLibrary"]),
        .target(name: "040", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "040Tests", dependencies: ["040", "TestLibrary"]),
        .target(name: "041", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "041Tests", dependencies: ["041", "TestLibrary"]),
        .target(name: "042", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "042Tests", dependencies: ["042", "TestLibrary"]),
        .target(name: "043", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "043Tests", dependencies: ["043", "TestLibrary"]),
        .target(name: "044", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "044Tests", dependencies: ["044", "TestLibrary"]),
        .target(name: "045", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "045Tests", dependencies: ["045", "TestLibrary"]),
        .target(name: "046", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "046Tests", dependencies: ["046", "TestLibrary"]),
        .target(name: "047", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "047Tests", dependencies: ["047", "TestLibrary"]),
        .target(name: "048", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "048Tests", dependencies: ["048", "TestLibrary"]),
        .target(name: "049", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "049Tests", dependencies: ["049", "TestLibrary"]),
        .target(name: "050", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "050Tests", dependencies: ["050", "TestLibrary"]),
        .target(name: "051", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "051Tests", dependencies: ["051", "TestLibrary"]),
        .target(name: "052", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "052Tests", dependencies: ["052", "TestLibrary"]),
        .target(name: "053", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "053Tests", dependencies: ["053", "TestLibrary"]),
        .target(name: "054", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "054Tests", dependencies: ["054", "TestLibrary"]),
        .target(name: "055", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "055Tests", dependencies: ["055", "TestLibrary"]),
        .target(name: "056", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "056Tests", dependencies: ["056", "TestLibrary"]),
        .target(name: "057", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "057Tests", dependencies: ["057", "TestLibrary"]),
        .target(name: "058", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "058Tests", dependencies: ["058", "TestLibrary"]),
        .target(name: "059", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "059Tests", dependencies: ["059", "TestLibrary"]),
        .target(name: "060", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "060Tests", dependencies: ["060", "TestLibrary"]),
        .target(name: "061", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "061Tests", dependencies: ["061", "TestLibrary"]),
        .target(name: "062", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "062Tests", dependencies: ["062", "TestLibrary"]),
        .target(name: "063", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "063Tests", dependencies: ["063", "TestLibrary"]),
        .target(name: "064", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "064Tests", dependencies: ["064", "TestLibrary"]),
        .target(name: "065", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "065Tests", dependencies: ["065", "TestLibrary"]),
        .target(name: "066", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "066Tests", dependencies: ["066", "TestLibrary"]),
        .target(name: "067", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "067Tests", dependencies: ["067", "TestLibrary"]),
        .target(name: "068", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "068Tests", dependencies: ["068", "TestLibrary"]),
        .target(name: "069", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "069Tests", dependencies: ["069", "TestLibrary"]),
        .target(name: "070", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "070Tests", dependencies: ["070", "TestLibrary"]),
        .target(name: "071", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "071Tests", dependencies: ["071", "TestLibrary"]),
        .target(name: "072", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "072Tests", dependencies: ["072", "TestLibrary"]),
        .target(name: "073", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "073Tests", dependencies: ["073", "TestLibrary"]),
        .target(name: "074", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "074Tests", dependencies: ["074", "TestLibrary"]),
        .target(name: "075", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "075Tests", dependencies: ["075", "TestLibrary"]),
        .target(name: "076", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "076Tests", dependencies: ["076", "TestLibrary"]),
        .target(name: "077", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "077Tests", dependencies: ["077", "TestLibrary"]),
        .target(name: "078", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "078Tests", dependencies: ["078", "TestLibrary"]),
        .target(name: "079", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "079Tests", dependencies: ["079", "TestLibrary"]),
        .target(name: "080", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "080Tests", dependencies: ["080", "TestLibrary"]),
        .target(name: "081", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "081Tests", dependencies: ["081", "TestLibrary"]),
        .target(name: "082", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "082Tests", dependencies: ["082", "TestLibrary"]),
        .target(name: "083", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "083Tests", dependencies: ["083", "TestLibrary"]),
        .target(name: "084", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "084Tests", dependencies: ["084", "TestLibrary"]),
        .target(name: "085", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "085Tests", dependencies: ["085", "TestLibrary"]),
        .target(name: "086", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "086Tests", dependencies: ["086", "TestLibrary"]),
        .target(name: "087", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "087Tests", dependencies: ["087", "TestLibrary"]),
        .target(name: "088", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "088Tests", dependencies: ["088", "TestLibrary"]),
        .target(name: "089", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "089Tests", dependencies: ["089", "TestLibrary"]),
        .target(name: "090", swiftSettings: [.unsafeFlags(["-Ounchecked"])]),
        .testTarget(name: "090Tests", dependencies: ["090", "TestLibrary"]),
        .target(name: "TestLibrary", path: "Tests/TestLibrary"),
    ]
)
